### ISSUE TITLE
Timezone problems

### ISSUE THREAD

**Issue by NatTuck** [CodeGrade/bottlenose#15] opened 2017-05-05 14:07 UTC
ccis:  blerner commented on Mar 15

From a student:

> Hi!
> 
> I found you a bug in Bottlenose:
> 
> I have my machine's time set to display in UTC (long story) and, although the due dates, etc. on the site show up in the correct time zone; on the submission page itself I am warned that I am past the due date because my local time (21:30ish) is past the local time of the due date (21:00) even though the real time is before the due date (2:00 UTC)
> 
> The due dates, etc. are all rendered correctly everywhere else.
>

**Comment by blerner** [comment] 2017-06-03 17:48
I think this will be largely fixed by removing all uses of `strftime` in .html.erb files, and replacing them with `.iso8601` calls instead.  Need to doublecheck that this doesn't screw up date versus datetime issues, but it seems to be mostly working for me so far.

**Comment by blerner** [comment] 2018-05-09 19:55
I think this is resolved and fixes are merged. Closing until a student finds a new problem with it.

**Closed by blerner** 2018-05-09 19:55 UTC

**Comment by avr1** [comment] 2021-06-02 20:36
In OOD this summer, some students in different time zones are running into problems submitting based on their time zone. For example, one student mentioned that they received the following message: "It is now past the due date and time for this assignment, and your submission will be considered late. Are you sure you want to submit?"  I haven't tried to reproduce it, but it appears that a version of this problem is still lingering.

**Comment by blerner** [comment] 2021-06-02 21:28
That's a different variant of this problem, I think.  There are still some timezone issues at play, but figuring out how to resolve them is...tricky at the moment.
