### ISSUE TITLE
Add the function to "delete" section(s) when creating a new course

### ISSUE THREAD

**Issue by xingyif** [CodeGrade/bottlenose#58] opened 2017-05-24 21:06 UTC
When the user is creating a new course, he/she can `Add Section` under `Sections` Tab. However, user is currently unable to delete the section if the section is accidentally added.

![screen shot 2017-05-24 at 17 04 30](https://cloud.githubusercontent.com/assets/15064985/26425528/18561848-40a3-11e7-89d5-77f31bd6190b.png)

**Comment by blerner** [comment] 2017-05-29 04:18
Dupe of #51

**Closed by blerner** 2017-05-29 04:18 UTC
